### ISSUE TITLE
Docs List 작성

### ISSUE THREAD

**Issue by RyouJisu** [18-2-SKKU-OSS/2018-2-OSS-E4#19]
Docs List 작성 중
파일 링크 연결하는 것은 추후에 완성하겠습니다.
일단 리스트 참고해주세요

**Comment by Taeeunn** [comment]
번역할 파일 작성해달라는 issue close해주세요~

**Comment by Taeeunn** [comment]
자기가 번역 완료한 파일은 취소선 긋고 옆에 링크도 자기가 달아주세요 지수가 너무 많다네요 ㅎㅎ
이제까지 한 것은 제가 여러분 대신 해드렸습니다 ㅎㅎ^^
