### ISSUE TITLE
각자 번역할 파일 선택해주세요

### ISSUE THREAD

**Issue by RyouJisu** [18-2-SKKU-OSS/2018-2-OSS-E4#2]
세린이가 정리한 문서들 중에서 각자 번역할 파일 선택하고 밑에 답글로 달아주세요.

**Comment by serin16** [comment]
### Docs List
**Get Started**

...(Translated)

learn-cockroachdb-sql.md

	**Build an app**
		build-an-app-with-cockroachdb.md
		...
		build-a-java-app-with-cockroachdb-hibernate.md
		build-a-c++-app-with-cockroachdb.md
		...

**Explore Features**
	demo-data-replication.md
	demo-fault-tolerance-and-recovery.md
	demo-automatic-rebalancing.md
	demo-serializable.md
	demo-automatic-cloud-migration.md
	demo-follow-the-workload.md
	orchestrate-a-local-cluster-with-kubernetes-insecure.md
	demo-json-support.md
	third-party-database-tools.md

**Deploy**
	recommended-production-settings.md	
	deploy-a-test-cluster.md
		**Manual Deployment**
			manual-deployment.md
			deploy-cockroachdb-on-premises.md
			deploy-cockroachdb-on-aws.md
			….
	See More: https://www.cockroachlabs.com/docs/stable -> GUIDES

**Comment by tjddud3345** [comment]
짝짝짝

**Comment by melrose98** [comment]
a

**Comment by melrose98** [comment]
build-an-app-with-cockroachdb.md

**Comment by Taeeunn** [comment]
cockroach-commands.md
alter-database.md
번역
![1466958523870](https://user-images.githubusercontent.com/32799078/49152073-0bc48b80-f355-11e8-8434-315a6896b760.gif)

**Comment by Taeeunn** [comment]
번역 다 끝나고 마지막 commit할 때는 commit message를 파일이름 + /* Translated into Korean */
으로 해주세요~
예를 들어 cockroach-commands.md 일 경우
commit message를 cockroach-commands.md /* Translated into Korean */으로 해주세요~
