### ISSUE TITLE
[번역완료] kubernetes-performance.md

### ISSUE THREAD

**Issue by RyouJisu** [18-2-SKKU-OSS/2018-2-OSS-E4#75]
12/07 번역 시작

**Comment by RyouJisu** [comment]
[kubernetes-performance.md](https://github.com/18-2-SKKU-OSS/2018-2-OSS-E4/blob/master/docs/v2.1/kubernetes-performance.md)

**Comment by Taeeunn** [comment]
빨리하세요^________^

**Comment by RyouJisu** [comment]
너무 길어여......ㅠㅠㅠㅠㅠㅠ

**Comment by Taeeunn** [comment]
나처럼 몇시간씩 하면 다할수있어^^

**Comment by Taeeunn** [comment]
엥 모르고 close함 ㅈㅅㅈㅅ........ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by RyouJisu** [comment]
12/09 번역완료
