### ISSUE TITLE
[Notice] 발표 준비 관련

### ISSUE THREAD

**Issue by Taeeunn** [18-2-SKKU-OSS/2018-2-OSS-E4#83]
발표 준비 상황도 issue에 올리고 다이어리에도 올리고 해주세요~

**Comment by jisuryou** [comment]
최종 발표 자료:
[OSS 발표 자료_SQL_CloudNative_issue및해결사항_.docx](https://github.com/18-2-SKKU-OSS/2018-2-OSS-E4/files/2666555/OSS._SQL_CloudNative_issue._.docx)
