### ISSUE TITLE
[Notice] 원본 프로젝트에 issue 올릴 내용 작성

### ISSUE THREAD

**Issue by melrose98** [18-2-SKKU-OSS/2018-2-OSS-E4#94]
번역하면서 영어로 된 원본 파일에서 오류를 발견한 사람들은 댓글로 달아주세요!
모아서 원본 프로젝트에 이슈열기 할 생각입니당

형식
[파일명.md]
(링크) **원본 프로젝트인 cockroachdb의 링크여야함!!
오류 내용, 수정 방안 등 영어로 작성.

**Comment by Taeeunn** [comment]
있었는데요, 없었습니다.

**Comment by melrose98** [comment]
> 있었는데요, 없었습니다.

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by melrose98** [comment]
없으면 마감할게요~
